

controller_server:
  ros__parameters:
    publish_feedback: False
    use_sim_time: True
    controller_frequency: 20.0
    progress_checker_plugin: "progress_checker"
    goal_checker_plugin: "goal_checker"
    controller_plugins: ["DynamicFollowPath"]
    DynamicFollowPath:
      plugin: "teb_local_planner::TebLocalPlannerROS"
      footprint_model:
        type: "line"
        line_start: [0.050000000000000044, 0.0] # for type "line"
        line_end: [2.5999999999999996, 0.0] # for type "line"
      min_obstacle_dist: 0.5
      include_dynamic_obstacles:  True
      obstacle_poses_affected: 25
      inflation_dist: 0.1
      costmap_converter_plugin: costmap_converter::CostmapToPolygonsDBSMCCH
      costmap_converter_spin_thread: True
      costmap_converter_rate: 15
      enable_homotopy_class_planning: True
      enable_multithreading: True
    #  weight_obstacle: 100.0
      control_look_ahead_poses: 3
      prevent_look_ahead_poses_near_goal: 2
      dt_ref: 0.3
      dt_hysteresis: 0.1
      global_plan_overwrite_orientation: False
      feasibility_check_no_poses: 4
    ###
      optimization_verbose: False
      teb_autoresize: True
      min_samples: 3
      max_samples: 50
      max_global_plan_lookahead_dist: 4.0
      visualize_hc_graph: False
      max_vel_x: 0.8
      max_vel_x_near_goal: 0.2
      max_vel_x_backwards: 0.3
      max_vel_x_backwards_near_goal: 0.2
      max_vel_theta: 0.6
      max_vel_theta_near_goal: 0.1
      acc_lim_x: 0.5
      acc_lim_theta: 0.5
      xy_goal_tolerance: 0.2
      yaw_goal_tolerance: 0.1
      global_plan_viapoint_sep: 0.4
      weight_viapoint: 5.0
      slowdown_dist_near_goal: 1.5
      no_inner_iterations: 5
      no_outer_iterations: 4
      max_number_classes: 4
      min_turning_radius: 0.2


controller_server_rclcpp_node:
  ros__parameters:
    use_sim_time: True


local_costmap:
  local_costmap:
    ros__parameters:
      use_sim_time: True
      global_frame: map
      plugins: ["obstacle_layer"]
      obstacle_layer.plugin: "nav2_costmap_2d::ObstacleLayer"
      rolling_window: False
      width: 8
      height: 8
      resolution: 2.0
      robot_radius: 0.25
      obstacle_layer:
        enabled: True
        observation_sources: scan
      always_send_full_costmap: True
  local_costmap_client:
    ros__parameters:
      use_sim_time: True
  local_costmap_rclcpp_node:
    ros__parameters:
      use_sim_time: True



bt_navigator:
  ros__parameters:
    use_sim_time: True
    global_frame: map
    robot_base_frame: base_link
    odom_topic: /odom
    default_bt_xml_filename: "/code/ros2_ws/install/nav2_bt_navigator/share/nav2_bt_navigator/behavior_trees/navigate_w_replanning_distance.xml"
    plugin_lib_names:
    - nav2_compute_path_to_pose_action_bt_node
    - nav2_follow_path_action_bt_node
    - nav2_back_up_action_bt_node
    - nav2_spin_action_bt_node
    - nav2_wait_action_bt_node
    - nav2_clear_costmap_service_bt_node
    - nav2_is_stuck_condition_bt_node
    - nav2_goal_reached_condition_bt_node
    - nav2_goal_updated_condition_bt_node
    - nav2_initial_pose_received_condition_bt_node
    - nav2_reinitialize_global_localization_service_bt_node
    - nav2_rate_controller_bt_node
    - nav2_distance_controller_bt_node
    - nav2_speed_controller_bt_node
    - nav2_truncate_path_action_bt_node
    - nav2_goal_updater_node_bt_node
    - nav2_recovery_node_bt_node
    - nav2_pipeline_sequence_bt_node
    - nav2_round_robin_node_bt_node
    - nav2_transform_available_condition_bt_node
    - nav2_time_expired_condition_bt_node
    - nav2_distance_traveled_condition_bt_node