

controller_server:
  ros__parameters:
    publish_feedback: False
    use_sim_time: True
    controller_frequency: 20.0
    progress_checker_plugin: "progress_checker"
    goal_checker_plugin: "goal_checker"
    controller_plugins: ["DynamicFollowPath"]
    DynamicFollowPath:
      plugin: "teb_local_planner::TebLocalPlannerROS"
      footprint_model:
        type: "line"
        line_start: [0.10000000000000003, 0.0] # for type "line"
        line_end: [2.56, 0.0] # for type "line"
      min_obstacle_dist: 0.5
      include_dynamic_obstacles:  True
      obstacle_poses_affected: 25
      inflation_dist: 0.1
      costmap_converter_plugin: costmap_converter::CostmapToPolygonsDBSMCCH
      costmap_converter_spin_thread: True
      costmap_converter_rate: 15
      enable_homotopy_class_planning: True
      enable_multithreading: True
    #  weight_obstacle: 100.0
      control_look_ahead_poses: 3
      prevent_look_ahead_poses_near_goal: 2
      dt_ref: 0.3
      dt_hysteresis: 0.1
      global_plan_overwrite_orientation: False
      feasibility_check_no_poses: 4
    ###
      optimization_verbose: False
      teb_autoresize: True
      min_samples: 3
      max_samples: 50
      max_global_plan_lookahead_dist: 4.0
      visualize_hc_graph: False
      max_vel_x: 0.8
      max_vel_x_near_goal: 0.2
      max_vel_x_backwards: 0.3
      max_vel_x_backwards_near_goal: 0.2
      max_vel_theta: 0.6
      max_vel_theta_near_goal: 0.1
      acc_lim_x: 0.5
      acc_lim_theta: 0.5
      xy_goal_tolerance: 0.2
      yaw_goal_tolerance: 0.1
      global_plan_viapoint_sep: 0.4
      weight_viapoint: 5.0
      slowdown_dist_near_goal: 1.5
      no_inner_iterations: 5
      no_outer_iterations: 4
      max_number_classes: 4


controller_server_rclcpp_node:
  ros__parameters:
    use_sim_time: True


local_costmap:
  local_costmap:
    ros__parameters:
      use_sim_time: True
      global_frame: map
      plugins: ["obstacle_layer", "static_layer"]
      obstacle_layer.plugin: "nav2_costmap_2d::ObstacleLayer"
      rolling_window: False
      width: 8
      height: 8
      resolution: 2.0
      robot_radius: 0.25
      obstacle_layer:
        enabled: True
        observation_sources: scan
      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        map_subscribe_transient_local: True
        map_topic: map
      always_send_full_costmap: True
  local_costmap_client:
    ros__parameters:
      use_sim_time: True
  local_costmap_rclcpp_node:
    ros__parameters:
      use_sim_time: True