amcl:
  ros__parameters:
    use_sim_time: True
    alpha1: 0.2
    alpha2: 0.2
    alpha3: 0.2
    alpha4: 0.2
    alpha5: 0.2
    base_frame_id: "base_footprint"
    beam_skip_distance: 0.5
    beam_skip_error_threshold: 0.9
    beam_skip_threshold: 0.3
    do_beamskip: false
    global_frame_id: "map"
    lambda_short: 0.1
    laser_likelihood_max_dist: 2.0
    laser_max_range: 100.0
    laser_min_range: -1.0
    laser_model_type: "likelihood_field"
    max_beams: 60
    max_particles: 2000
    min_particles: 500
    odom_frame_id: "odom"
    pf_err: 0.05
    pf_z: 0.99
    recovery_alpha_fast: 0.0
    recovery_alpha_slow: 0.0
    resample_interval: 1
    robot_model_type: "differential"
    save_pose_rate: 0.5
    sigma_hit: 0.2
    tf_broadcast: true
    transform_tolerance: 1.0
    update_min_a: 0.2
    update_min_d: 0.25
    z_hit: 0.5
    z_max: 0.05
    z_rand: 0.5
    z_short: 0.05

amcl_map_client:
  ros__parameters:
    use_sim_time: True

amcl_rclcpp_node:
  ros__parameters:
    use_sim_time: True

bt_navigator:
  ros__parameters:
    bt_xml_filename: "navigate_w_replanning.xml"
    plugin_lib_names:
    - nav2_compute_path_to_pose_action_bt_node
    - nav2_follow_path_action_bt_node
    - nav2_back_up_action_bt_node
    - nav2_spin_action_bt_node
    - nav2_wait_action_bt_node
    - nav2_clear_costmap_service_bt_node
    - nav2_is_stuck_condition_bt_node
    - nav2_goal_reached_condition_bt_node
    - nav2_initial_pose_received_condition_bt_node
    - nav2_reinitialize_global_localization_service_bt_node
    - nav2_rate_controller_bt_node
    - nav2_recovery_node_bt_node
    - nav2_pipeline_sequence_bt_node
    - nav2_round_robin_node_bt_node

bt_navigator_rclcpp_node:
  ros__parameters:
    use_sim_time: True

controller_server:
  ros__parameters:
    use_sim_time: True
    controller_frequency: 20.0
    controller_plugin_types: ["teb_local_planner::TebLocalPlannerROS"]
    controller_plugin_ids: ["DynamicFollowPath"]
    DynamicFollowPath.footprint_model.type: "line"
    DynamicFollowPath:
      footprint_model:
        line_start: [-0.1, 0.0] # for type "line"
        line_end: [0.1, 0.0] # for type "line"
    DynamicFollowPath.footprint_model.radius: 0.25
    DynamicFollowPath.min_obstacle_dist: 0.3
    DynamicFollowPath.obstacle_poses_affected: 900
    DynamicFollowPath.inflation_dist: 0.1
    DynamicFollowPath.costmap_converter_plugin: costmap_converter::CostmapToPolygonsDBSMCCH
    DynamicFollowPath.costmap_converter_spin_thread: True
    DynamicFollowPath.costmap_converter_rate: 15
    DynamicFollowPath.enable_homotopy_class_planning: True
    DynamicFollowPath.enable_multithreading: True
    #DynamicFollowPath.weight_obstacle: 100.0
    DynamicFollowPath.control_look_ahead_poses: 3
    DynamicFollowPath.prevent_look_ahead_poses_near_goal: 2
    DynamicFollowPath.dt_ref: 0.3
    DynamicFollowPath.dt_hysteresis: 0.1
    DynamicFollowPath.global_plan_overwrite_orientation: False
    DynamicFollowPath.feasibility_check_no_poses: 4
    ###
    DynamicFollowPath.optimization_verbose: False
    DynamicFollowPath.teb_autoresize: True
    DynamicFollowPath.min_samples: 3
    DynamicFollowPath.max_samples: 50
    DynamicFollowPath.max_global_plan_lookahead_dist: 4.0
    DynamicFollowPath.visualize_hc_graph: False
    DynamicFollowPath.max_vel_x: 0.8
    DynamicFollowPath.max_vel_x_near_goal: 0.2
    DynamicFollowPath.max_vel_theta: 0.6
    DynamicFollowPath.max_vel_theta_near_goal: 0.1
    DynamicFollowPath.acc_lim_x: 0.5
    DynamicFollowPath.acc_lim_theta: 0.5
    DynamicFollowPath.xy_goal_tolerance: 0.2
    DynamicFollowPath.yaw_goal_tolerance: 0.1
    DynamicFollowPath.global_plan_viapoint_sep: 0.4
    DynamicFollowPath.weight_viapoint: 5.0

costmap_converter:
  ros__parameters:
    use_sim_time: True

controller_server_rclcpp_node:
  ros__parameters:
    use_sim_time: True
local_costmap:

  local_costmap:
    ros__parameters:
      use_sim_time: True
      global_frame: map
      plugin_names: ["obstacle_layer", "inflation_layer"]
      plugin_types: ["nav2_costmap_2d::ObstacleLayer", "nav2_costmap_2d::InflationLayer"]
      rolling_window: true
      width: 8
      height: 8
      resolution: 0.2
      robot_radius: 0.25
      inflation_layer:
        cost_scaling_factor: 3.0
      obstacle_layer:
        enabled: True
        observation_sources: scan
        scan:
          topic: /scan
          max_obstacle_height: 2.0
          clearing: True
          marking: True
          data_type: "LaserScan"
      static_layer:
        map_subscribe_transient_local: True
      always_send_full_costmap: True
  local_costmap_client:
    ros__parameters:
      use_sim_time: True
  local_costmap_rclcpp_node:
    ros__parameters:
      use_sim_time: True

global_costmap:
  global_costmap:
    ros__parameters:
      use_sim_time: True
      plugin_names: ["static_layer", "obstacle_layer", "voxel_layer", "inflation_layer"]
      plugin_types: ["nav2_costmap_2d::StaticLayer", "nav2_costmap_2d::ObstacleLayer", "nav2_costmap_2d::VoxelLayer", "nav2_costmap_2d::InflationLayer"]
      robot_radius: 1.0
      obstacle_layer:
        enabled: True
        observation_sources: scan
        scan:
          topic: /scan
          max_obstacle_height: 2.0
          clearing: True
          marking: True
          data_type: "LaserScan"
      voxel_layer:
        enabled: True
        publish_voxel_map: True
        origin_z: 0.0
        z_resolution: 0.2
        z_voxels: 10
        max_obstacle_height: 2.0
        mark_threshold: 0
        observation_sources: pointcloud
        pointcloud:
          topic: /intel_realsense_r200_depth/points
          max_obstacle_height: 2.0
          clearing: True
          marking: True
          data_type: "PointCloud2"
      static_layer:
        map_subscribe_transient_local: True
      always_send_full_costmap: True
  global_costmap_client:
    ros__parameters:
      use_sim_time: True
  global_costmap_rclcpp_node:
    ros__parameters:
      use_sim_time: True

map_server:
  ros__parameters:
    use_sim_time: True
    yaml_filename: "turtlebot3_world.yaml"

planner_server:
  ros__parameters:
    use_sim_time: True
    tolerance: 0.0
    use_astar: false

planner_server_rclcpp_node:
  ros__parameters:
    use_sim_time: True

robot_state_publisher:
  ros__parameters:
    use_sim_time: True
